import { useState } from "react";

import { Loader } from "../components";

const Home = () => {
  const [isLoading, setLoading] = useState(false);
  const [searchText, setSearchText] = useState("dfsdfsdf");

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          Community Showcase
        </h1>
        <p className="mt-2 text-gray-600 text-lg max-w[500px]">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI 🤖
        </p>
      </div>
      <div className="mt-16">Form</div>
      <div className="mt-10">
        {isLoading ? (
          <Loader />
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium  text-gray-500 text-xl mb-3">
                Showing results for{" "}
                <span className="text-gray-900">{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              Render posts...
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
